### ISSUE TITLE
task: make output filename and voxel spacing configurable

### ISSUE THREAD

**Issue by alisterburt** [teamtomo/ttmask#13]
@milesagraham great work here - it would be useful to make the output file and voxel spacings configurable for each program rather than hard coded

https://github.com/teamtomo/ttmask/blob/ef0d4f4d3f43e2d985b9f938ad85f924db1da7c5/src/ttmask/sphere.py#L41

https://github.com/teamtomo/ttmask/blob/ef0d4f4d3f43e2d985b9f938ad85f924db1da7c5/src/ttmask/cylinder.py#L46

**Comment by milesagraham** [comment]
Thanks, have done this now :)

**Comment by alisterburt** [comment]
Closed by #13
