### ISSUE TITLE
Add README/docs

### ISSUE THREAD

**Issue by alisterburt** [teamtomo/ttmask#23]
We should think about adding a more descriptive README or even some docs

@milesagraham are you interested in learning how to write deploy docs sites like https://teamtomo.org/starfile ?

If so we can jump on a call to do that one afternoon UK time next week

**Comment by milesagraham** [comment]
Sounds great - I'll message you to set up a time

**Comment by milesagraham** [comment]
Closing for now. We can open up fresh issues for any errors in the docs I uploaded
